# Generated by Django 4.2.21 on 2025-05-19 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('secondName', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255)),
                ('isVerified', models.BooleanField(default=False)),
                ('verificationCode', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('role', models.CharField(blank=True, choices=[('employer', 'Employer'), ('jobseeker', 'JobSeeker'), ('superAdmin', 'SuperAdmin'), ('admin', 'Admin')], max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
