# Generated by Django 4.2.21 on 2025-06-11 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verificationCode',
            field=models.UUIDField(blank=True, db_column='verificationCode', default=uuid.uuid4, editable=False, null=True),
        ),
    ]
