# Generated by Django 4.2.21 on 2025-07-02 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_alter_user_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='user',
            name='dateJoined',
            field=models.DateTimeField(auto_now_add=True, db_column='dateJoined', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isStaff',
            field=models.BooleanField(db_column='isStaff', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isSuperuser',
            field=models.BooleanField(db_column='isSuperuser', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(blank=True, db_column='lastLogin', null=True),
        ),
    ]
