# Generated by Django 4.2.21 on 2025-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=45, null=True)),
                ('year_of_joining', models.DateField(blank=True, null=True)),
                ('year_of_completion', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('bio_data', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_seeker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobSeekerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(blank=True, max_length=45, null=True)),
                ('upload_path', models.CharField(blank=True, max_length=500, null=True)),
                ('awarded_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jobseeker_certification',
                'managed': False,
            },
        ),
    ]
