# Generated by Django 4.2.21 on 2025-07-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_by'),
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(db_column='users_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to='users.user'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
