# Generated by Django 4.2.21 on 2025-07-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_by'),
        ('jobseeker', '0002_jobseeker_user_alter_jobseeker_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.user'),
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.user'),
        ),
    ]
