# Generated by Django 5.1.9 on 2025-06-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_jobseekercertification_options_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekercertification',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='awarded_date',
            field=models.DateField(blank=True, db_column='awardedDate', null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt'),
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt'),
        ),
        migrations.AlterField(
            model_name='jobseekercertification',
            name='upload_path',
            field=models.CharField(blank=True, db_column='uploadPath', max_length=500, null=True),
        ),
    ]
