# Generated by Django 4.2.21 on 2025-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekercertification',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='jobseekercertification',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='jobseekercertification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekercertification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
