# Generated by Django 5.1.9 on 2025-06-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_jobseekercertification_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekercertification',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='jobseekercertification',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
