# Generated by Django 4.2.21 on 2025-07-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_remove_jobseekercertification_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekercertification',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='jobseekercertification',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
