# Generated by Django 4.2.21 on 2025-07-28 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('CAREERJET', 'CareerJet')], max_length=20)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['source'], name='job_scraper_source_55964a_idx'), models.Index(fields=['title'], name='job_scraper_title_aa5a3c_idx'), models.Index(fields=['company'], name='job_scraper_company_c9a117_idx')],
            },
        ),
    ]
