# Generated by Django 4.2.21 on 2025-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=45)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skills',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffeciency_level', models.CharField(blank=True, choices=[('begginner', 'Begginner'), ('intermediate', 'Intermediate'), ('midlevel', 'Midlevel'), ('proffessional', 'Professional')], max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'db_table': 'skillSet',
                'managed': True,
            },
        ),
    ]
