# Generated by Django 5.1.9 on 2025-06-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'managed': True},
        ),
    ]
