# Generated by Django 5.1.9 on 2025-06-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_options_alter_skillset_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='skillName',
        ),
        migrations.RenameField(
            model_name='skillset',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='skillset',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='skillset',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillset',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
