# Generated by Django 4.2.21 on 2025-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        ('skills', '0001_initial'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='recruiter',
            field=models.ForeignKey(db_column='recruiter_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='recruiter.recruiter'),
        ),
        migrations.AlterUniqueTogether(
            name='jobpostingskill',
            unique_together={('job_posting', 'skill')},
        ),
    ]
