# Generated by Django 4.2.21 on 2025-07-28 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobseeker', '0001_initial'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=45)),
                ('companyLogo', models.CharField(blank=True, max_length=500, null=True)),
                ('industry', models.CharField(blank=True, max_length=250, null=True)),
                ('contactInfo', models.CharField(blank=True, max_length=250, null=True)),
                ('companyEmail', models.EmailField(max_length=254, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('isVerified', models.BooleanField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recruiter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecruiterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('job_seeker', 'Job Seeker')], default='recruiter', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('intrested', 'Intrested'), ('applied', 'Applied'), ('interviewed', 'Interviewed'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='shortlisted', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('interviewDate', models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 1, 0, 0), null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('job_posting', models.ForeignKey(blank=True, db_column='job_posting_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_job_posting', to='job_posting.jobposting')),
                ('job_seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='jobseeker.jobseeker')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter')),
            ],
            options={
                'db_table': 'recruiter_tracking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecruiterDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=45, null=True)),
                ('upload_path', models.FileField(blank=True, null=True, upload_to='recruiter_docs/%Y/%m/%d/')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter')),
            ],
            options={
                'db_table': 'recruiter_doc',
                'managed': True,
            },
        ),
    ]
