# Generated by Django 4.2.21 on 2025-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdoc',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to='users.user'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.ForeignKey(blank=True, db_column='users_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='users.user'),
        ),
    ]
