# Generated by Django 5.1.9 on 2025-06-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recruiterdoc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recruitertracking',
            options={'managed': True},
        ),
    ]
