# Generated by Django 5.1.9 on 2025-06-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_alter_recruiter_options_alter_recruiterdoc_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='recruiterdoc',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='recruiterdoc',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='recruitertracking',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='recruitertracking',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.AddField(
            model_name='recruiterdoc',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
        migrations.AddField(
            model_name='recruiterdoc',
            name='verifiedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterdoc',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitertracking',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitertracking',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter'),
        ),
        migrations.AlterField(
            model_name='recruiterdoc',
            name='upload_path',
            field=models.FileField(blank=True, null=True, upload_to='recruiter_docs/%Y/%m/%d/'),
        ),
        migrations.AlterModelTable(
            name='recruiterdoc',
            table='recruiter_doc',
        ),
    ]
