# Generated by Django 5.1.9 on 2025-06-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_alter_recruiter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'managed': True},
        ),
    ]
