# Generated by Django 5.1.9 on 2025-06-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0005_rename_company_email_recruiter_companyemail_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.ForeignKey(blank=True, db_column='users_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='users.user'),
        ),
        migrations.AlterField(
            model_name='recruiterdoc',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to='users.user'),
        ),
        migrations.AlterField(
            model_name='recruitertracking',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='users.user'),
        ),
    ]
