# Generated by Django 5.1.9 on 2025-06-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_rename_created_at_jobseekercertification_createdat_and_more'),
        ('recruiter', '0007_fix_verifiedBy_column'),
        ('users', '0002_user_is_active_alter_user_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdoc',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to='users.user'),
        ),
        migrations.AlterField(
            model_name='recruitertracking',
            name='job_seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='jobseeker.jobseeker'),
        ),
    ]
