# Generated by Django 4.2.21 on 2025-07-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
        ('recruiter', '0008_alter_recruiterdoc_verifiedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitertracking',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='job_posting.jobposting'),
        ),
    ]
