# Generated by Django 4.2.21 on 2025-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_recruitertracking_job_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitertracking',
            old_name='job_posting',
            new_name='job_posting_id',
        ),
        migrations.AlterField(
            model_name='recruitertracking',
            name='status',
            field=models.CharField(blank=True, choices=[('intrested', 'Intrested'), ('applied', 'Applied'), ('interviewed', 'Interviewed'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='shortlisted', max_length=20, null=True),
        ),
    ]
