# Generated by Django 4.2.21 on 2025-07-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
        ('recruiter', '0010_rename_job_posting_recruitertracking_job_posting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitertracking',
            name='job_posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_job_posting', to='job_posting.jobposting'),
        ),
    ]
