# Generated by Django 4.2.21 on 2025-07-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_alter_recruitertracking_job_posting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitertracking',
            old_name='job_posting_id',
            new_name='job_posting',
        ),
    ]
