# Generated by Django 4.2.21 on 2025-07-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_rename_job_posting_id_recruitertracking_job_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitertracking',
            name='user_type',
            field=models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('job_seeker', 'Job Seeker')], default='recruiter', max_length=20, null=True),
        ),
    ]
