# Generated by Django 4.2.21 on 2025-07-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0014_recruitertracking_user_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recruitertracking',
            constraint=models.UniqueConstraint(condition=models.Q(('job_posting_id__isnull', False)), fields=('job_seeker_id', 'job_posting_id'), name='unique_job_application', violation_error_message="You've already applied to this position"),
        ),
    ]
