# Generated by Django 4.2.21 on 2025-07-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0015_recruitertracking_unique_job_application'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recruitertracking',
            name='unique_job_application',
        ),
    ]
